### ISSUE TITLE
US7 - Sort Itinerary by Date

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#14]
## Value proposition

As a backpacker
I want to sort my POIs (points of interest) by date
In order to keep track of all my plans

## Description

![Uploading image.png…]()

## Acceptance criteria

- [ ] At the top of the itinerary the user sees thumbnails for the POIs they saved on the suggestions page
- [ ] If the user hovers over a thumbnail the POI's name shows up in a pop up
- [ ] The user can add additional items 
- [ ] Below that all the dates of the trip show up
- [ ] Per drag and drop the user can put the POIs on top of the desired date
- [ ] They show up in text form
- [ ] If the user changes their mind, they can drag and drop the POIs to another day or change the order of POIs on that specific day
- [ ] The user can add their own items for each day

## Tasks

- [ ] Create a branch feat/itinerary-by-date
- [ ] Create an overview with all the dates the user entered for that specific trip
- [ ] Show Thumbnails of all POIs the user selected above the dates
- [ ] Make the thumbnails drag-and-drop-able
- [ ] Show the POIs name instead of the thumbnail, once the user places them
- [ ] Enable the user to change the POIs position later on
- [ ] Create a little button next to each day
- [ ] Enable the user to add additional items with a pop up
- [ ] Add those custom items to the respective date

**Comment by ninaassmann** [comment]
LGTM
I would love to see how you manage the drag and drop function
