### ISSUE TITLE
US8 - Sort Itinerary by Time

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#16]
## Value proposition

As a backpacker
I want to see my itinerary sorted by time
So I don't miss any important items (like fixed bookings)

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/370b4583-69f5-45f2-83c2-20128bb13818)

## Acceptance criteria

- [ ] Under each date the items with a fixed time are listed at the top
- [ ] The items with a time are sorted starting with the earliest time
- [ ] The date is displayed in 12-hour time format (am/pm)
- [ ] The time is listed in a second column for better readability
- [ ] Items with a long description take up several lines
- [ ] Under each date the items without a fixed time are listed in the order they were added

## Tasks

- [ ] Create a branch feat/sort-by-time
- [ ] Sort all items with a fixed time
- [ ] Change the time format to 12-hour format
- [ ] Add a second column where the time shows up (grid), aligned to the right
- [ ] Ensure that long descriptions will wrap
