### ISSUE TITLE
US9 - Edit and Delete Itinerary Items

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#17]
## Value proposition

As a backpacker
I want to be able to edit an delete itinerary items
In order to always keep my itinerary up to date when plans change

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/4b11cafe-c5a8-4762-bee8-ef4964ee3615)

## Acceptance criteria

- [ ] Each itinerary item has a red X button to delete it
- [ ] Each itinerary item can be clicked
- [ ] The item then becomes editable which is marked by the text being a light orange and a blinking I cursor
- [ ] Next to the text a blue Check button allows the user to submit their changes

## Tasks

- [ ] Create a new branch feat/edit-and-delete-itinerary
- [ ] Add a red X button to each itinerary item
- [ ] Delete the respective item from the list if the button is clicked
- [ ] Make each itinerary item a button
- [ ] On click a pop up opens on top of the item with an input field
- [ ] The blue Check button submits the changes and they will become visible in the itinerary

**Comment by FabianRuettgers** [comment]
My suggests : 

- It's a good practice to include a confirmation prompt when the user clicks the red X button to delete an itinerary item. This helps prevent accidental deletions.
- Add a button or option to cancel the editing process without saving changes. This is especially important for users who might want to discard their edits and keep the original item.
- Specify how you'll handle validation for edited itinerary items. Are there character limits, required fields, or other constraints that need to be addressed?
- Maybe hide the red X button when an item is being edited.

**Comment by MiejkeHoltermann** [comment]
Thank you for your detailed feedback. I made changes accordingly. It don't need any restrictions for edited items, since I already handled this for the existing items: Very long items just wrap normally and in case of a single long word they are cut off at the end of the column with three dots ...
