### ISSUE TITLE
US10 - Change the scrollboxes

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#18]
## Value proposition

As a backpacker
I want to always see the save button
So I don't have to scroll all the way down to end of the page every time I make a little adjustment

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] The scroll boxes for travel log, explore page and itinerary page are completely visible on the screen
- [ ] Below the scroll boxes the Save button is displayed so the user can save and exit anytime
- [ ] It the user scrolls through the items only the items move across the screen, not the Save button and not the heading

## Tasks

- [ ] Create a new branch feat/change-scrollboxes
- [ ] Create a smaller scrollbox for the travel log page
- [ ] The save button and heading are outside of the scrollbox
- [ ] Adapt the same construct for the explore and itinerary pages

## Size
S
