### ISSUE TITLE
US11 - Add Map View to Itinerary

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#19]
## Value proposition

As a backpacker
I want to be able to see all my itinerary items on a map
So that I can easily keep track of the geography of my journey

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/2a08164e-8afe-4c93-8c1c-ea72c80e3eb7)

## Acceptance criteria

- [ ] On the itinerary page the user can click a little map icon
- [ ] This takes the user to a new page where they can see a map of the destination
- [ ] For each item on their itinerary a marker is placed on the map
- [ ] The map icon turns into a list icon and takes the user back to their itinerary

## Tasks

- [ ] Create new branch feat/map-view
- [ ] Add a new page with a map (Open Street Map API)
- [ ] Change the map so that it shows the respective destination
- [ ] Add a map/list toggle button to itinerary and map page
- [ ] Make the itinerary items show up as markers in the map

## Size
L

**Comment by FabianRuettgers** [comment]
My suggestions:

- If the Open Street Map API requires an API key, make sure to handle its integration and management securely.
- Consider scenarios where the API might fail to load, or the map data might not be available. Plan for appropriate error handling in such cases.
- Evaluate the performance impact of loading the map and markers, especially if the itinerary contains a significant number of items.
- If there are many markers close together, consider implementing marker clustering to improve the map's readability.
- maybe Provide zoom and pan controls on the map so users can adjust their view based on their preferences and the density of markers.

**Comment by MiejkeHoltermann** [comment]
Thank you, those are really good tips! I implemented some of them, but I think the rest might be a separate user story. I'll keep it in mind for US12.
