### ISSUE TITLE
US 2 - 

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#2]
## Value proposition

As a backpacker
I want an add function
So that I can add new trips

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/53c3ae82-aa9f-463c-a0d1-fb23d291402d)

## Acceptance criteria

- [ ] The user can type a location into an input field
- [ ] The user can type a start and an end date into an input field
- [ ] The data can be submitted with a button
- [ ] The new trip shows up in the list under upcoming or passed trips depending on the date

## Tasks

- [ ] Create a branch feat/add-function
- [ ] Create a form
- [ ] Create a text input field for the location
- [ ] Create a date input field for the start and end date
- [ ] Create a submit button
- [ ] Read in the the submitted data
- [ ] Check today’s date
- [ ] Compare the trip’s dates to today’s date
- [ ] Decide whether the trip is upcoming or passed
- [ ] Create a new trip in the respective list

**Comment by ninaassmann** [comment]
maybe a second input for the end date in your wireframe
