### ISSUE TITLE
US12 - Fetch Sights from API

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#24]
## Value proposition

As a backpacker
I want to explore things to do in different locations
So I can plan trips all around the world

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/77ea40cd-b96e-4aff-8607-c677c758b5a7)

## Acceptance criteria

- [ ] When I click on a trip in my travel log the explore and itinerary page show the image, name and dates of the respective trips
- [ ] The list of things to do on the explore page is specifically for that destination

## Tasks

- [ ] Create new branch feat/fetch-sights
- [ ] Create a dynamic route for the explore page with useRouter
- [ ] Adjust image, name and dates in the header so they change dynamically
- [ ] Fetch the sights from the Open Street Map API
- [ ] Create error handling for the fetching
- [ ] Show a list of the sights for each location on that location's sight
- [ ] Delete the array which provided the sights data before
- [ ] Check extensively that everything works the way it did before only with the API data instead of the array

## Size
L
