### ISSUE TITLE
US13 - Create a Home Page

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#25]
## Value proposition

As a backpacker
I want to start the app with the most important features
So I get to the most interesting parts of the app with just one click

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/08b6a3fd-bb60-4e0b-a3d9-c8178a18cca1)

## Acceptance criteria

- [ ] When the user opens the app the new home page shows up first
- [ ] At the top of the home page a header with a generic travel picture, the app's logo and a link to the travel log (list of all trips) shows up
- [ ] Under the header the user can add a new trip via form
- [ ] Under the form a list of upcoming trips shows up with a preview picture, the location's name and a countdown for each trip
- [ ] Under the list a carousel with random destinations shows up with a preview picture and the location's name for each suggestion

## Tasks

- [ ] Create a new branch feat/homepage
- [ ] Create a new travel log page with the list of all trips which was the former home page
- [ ] Create a new page with a header incl. generic travel picture and the app's logo
- [ ] Add a link to the travel log (also add this link to every other page's header so the user can always go back to the travel log)
- [ ] Remove the form for new trips from the travel log page and display it on the new home page
- [ ] Copy the list of upcoming trips from the travel log page and display it on the new home page
- [ ] Display a carousel with random locations on the new home page (each location is a link that leads to an explore page with sights for the specific location)

## Size
L

**Comment by FabianRuettgers** [comment]
My suggestions: 

- Clarify how the carousel should behave. Does it auto-scroll, or do users need to manually navigate through the suggestions? Is there any specific order in which the random destinations are displayed?
- For the countdown of upcoming trips, consider whether the countdown updates in real-time or upon page load. 
- Think about potential error scenarios, such as what should happen if there are no upcoming trips to display or if the carousel can't load suggestions.
