### ISSUE TITLE
US14 - Trip Overview Page

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#26]
## Value proposition

As a backpacker
I want to see all features concerning my trip in one place
So I don't forget anything important

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/0273d8b3-c09a-4887-9b3a-7a479c14a5c7)

## Acceptance criteria

- [ ] When the user adds a new trip a trip overview page shows up with a text informing the user that they created a new trip
- [ ] Under that a button "Go Exploring" leads to the explore page for that trip
- [ ] Under that smaller buttons lead to the separate features for that trip, so far those are "Itinerary" and "Map"
- [ ] A button "Done" at the bottom of the page leads back to the home page
- [ ] The trip overview page also shows up when the user clicks on an existing trip, only without the message that they created a new trip, but with all the buttons

## Tasks

- [ ] Create a new branch feat/overview-page
- [ ] Create a new overview page
- [ ] Add a message "You created a new trip! Now we can start planning..." which only shows up for newly created trips
- [ ] Add an Explore button which leads to the respective explore page
- [ ] Add an Itinerary and Map button for the respective pages
- [ ] Add a Done link which looks like a button and takes the user back to the home page

## Size
S

**Comment by JanaS87** [comment]
looks good to me, I like your clean, modern minimalistic style 👍

**Comment by MiejkeHoltermann** [comment]
Thank you so much 😊
