### ISSUE TITLE
US15 - Expenses

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#27]
## Value proposition

As a backpacker
I want to save all my travel expenses
So I can keep track of my budget

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/f724b0fb-a5e5-4086-9563-2a22739cd311)

## Acceptance criteria

- [ ] When the user clicks on the Expenses button on the travel overview page the Expenses page opens
- [ ] Here all expenses are listed by date, showing the item and the amount (in Euros)
- [ ] The user can add new items to the list, edit and delete existing items

## Tasks

- [ ] Create a new branch feat/Expenses
- [ ] Create a new page Expenses
- [ ] Add a button to the trip overview page which links to the Expenses page
- [ ] List all items sorted by date (copy from Itinerary page)
- [ ] Insert add, edit and delete functions (copy from Itinerary page)

## Size
S

**Comment by JanaS87** [comment]
As I said before, I like it very much! Can't wait to see it in action :)
