### ISSUE TITLE
US 3 - Explore Function

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#3]
## Value proposition

As a backpacker
I want an explore function
So that I can see what there is to do at my desired location

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/e402f249-e905-4a88-848d-952a1b147950)

## Acceptance criteria

- [ ] The user can click on the upcoming trip
- [ ] On a separate page a list of things to do shows up
- [ ] The header shows a picture of the location, its name and the travel dates
- [ ] Each thing consists of a name and a preview picture
- [ ] The list scrolls down vertically only
- [ ] An Exit button takes the user back to the travel overview

## Tasks

- [ ] Create a branch feat/explore-function
- [ ] Create a new page
- [ ] Make the upcoming location a link to the new page
- [ ] Create a header with a picture of the location
- [ ] Add the location’s name and travel dates to the header
- [ ] Create an array with things to do at the location incl. pictures
- [ ] Show a list of the things to do incl. pictures
- [ ] Handle scrolling function
- [ ] Create an exit button that links back to the travel overview

**Comment by DorisW3** [comment]
looks really nice, the images are awesome! I want use the app instantly to plan a journey :-D
