### ISSUE TITLE
US 4 - Show details for things to do

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#4]
## Value proposition

As a backpacker
I want more details on the things to do
So that I can decide whether I’m interested

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/a282e8d3-f6d8-49db-b049-a9dfe1fa4b24)

## Acceptance criteria

- [ ] The user can click on a thing to do
- [ ] A pop up with details about the item shows up
- [ ] The pop up closes on another click

## Tasks

- [ ] Create a branch feat/details
- [ ] Add a details property to each item in the array
- [ ] Create a pop up that opens with a click on one item
- [ ] Make that pop up show the preview picture, name and details
- [ ] Make the pop up close with a click on that pop up

**Comment by FabianRuettgers** [comment]
Acceptance criteria 
- I would add something like "The pop-up window contains a preview picture, the name of the activity or attraction, and its details."

- define the scrolling direction, in this case vertically

Tasks

- consider handling scenarios where users click outside the pop-up or interact with multiple items rapidly. Decide whether the pop-up should close in such cases.

- Maybe implement accessibility features to ensure that users with disabilities can interact with the pop-up and its content.
