### ISSUE TITLE
US 5 - Add things to itinerary

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#5]
## Value proposition

As a backpacker
I want to add things to my itinerary
So that I remember what I want to do

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/976f604b-2056-447f-89c8-2c324efffbab)

## Acceptance criteria

- [ ] The user can click a button "Add to Trip" to add an item to their itinerary
- [ ] The item disappears from the list of suggestions
- [ ] A message shows up: “Saved to itinerary”
- [ ] After clicking a Save button a new page opens with a list of all saved items and the headline Itinerary

## Tasks

Create a branch feat/itinerary
Add a "Add to Trip" button to the details pop up of each item
Add a favorite property to the array of items
Add a function to the favorite button to set isFavorite to true
This function should also hide the item from the list
Create a new page
Create a headline (h2) "Itinerary"
Show all items where isFavorite is true
Change the Exit button to a Save button
Link the Save button to the new page

**Comment by alper92** [comment]
Hi Miejke, looking forward to see this, once it is done! I have nothing to add here. Much success!
