### ISSUE TITLE
US 3 - Sort new trips by current, passed and upcoming

### ISSUE THREAD

**Issue by MiejkeHoltermann** [MiejkeHoltermann/capstone-project#6]
## Value proposition

As a backpacker
I want to see my trips sorted by current, passed and upcoming trips
So that I quickly see which trips require my attention

## Description

![image](https://github.com/MiejkeHoltermann/capstone-project/assets/136608039/e5d9689b-0f25-4523-b325-210e19848b0d)

## Acceptance criteria

- [ ] All existing trips are sorted in three lists: Current Trips, Upcoming Trips and Passed Trips
- [ ] The lists can be opened and closed with a little arrow
- [ ] If a list is empty, it should say "You don't have any current/upcoming/passed trips yet."

## Tasks

- [ ] Create a new branch feat/sorting
- [ ] Check today’s date
- [ ] Compare a new trip's date to today’s date
- [ ] Decide whether the trip is current, upcoming or passed
- [ ] Sort the trip into the respective list
- [ ] Compare all existing trips' dates to today's date
- [ ] Decide whether the existing trips are current, upcoming or passed
- [ ] Sort the existing trips into the respective list
- [ ] Make the arrows next to all headlines toggle buttons to hide/show the respective list
- [ ] If a list is empty, show the respective message "You don't have any current/upcoming/passed trips yet."

**Comment by Roland-Hufnagel** [comment]
Hi. That's a good feature and a good US, too.
The only thing, I'm getting confused, is the tasks. You say: 'Compare a new trip's data to today's date' and in the headline: 
'Sort NEW trips...'.
I think this should not happen when creating a 'new' trip, but when rendering the list of existing trips.

**Comment by DorisW3** [comment]
This US looks great, Miejke! Do you mean "trips, which are currently planned" with "current trips"?
